default:
  emulator:
  core:
  options:
    videomode:      default
    ratio:          auto
    video_threaded: false
    smooth:         true
    rewind:         false
    bezel:          default
    forceNoBezel:   false

switch:
  emulator: citron
  core:     citron
  options:
    forceNoBezel: true